export const PoppinsExtraBoldItalic="Poppins-ExtraBoldItalic"
export const PoppinsExtraBold="Poppins-ExtraBold"
export const PoppinsBoldItalic="Poppins-BoldItalic"
export const PoppinsBold="Poppins-Bold"
export const PoppinsBlackItalic="Poppins-BlackItalic"
export const PoppinsBlack="Poppins-Black"
export const PoppinsItalic="Poppins-Italic"
export const PoppinsLightItalic="Poppins-LightItalic"
export const Poppins="Poppins-Medium"
export const PoppinsMediumItalic="Poppins-MediumItalic"
export const PoppinsRegular="Poppins-Regular"
export const PoppinsSemiBold="Poppins-SemiBold"
export const PoppinsSemiBoldItalic="Poppins-SemiBoldItalic"
export const PoppinsThin="Poppins-Thin"
export const PoppinsThinItalic="Poppins-ThinItalic"

