export const ONBOARDING = 'onboarding';
export const ROUTE_SIGNIN = 'signin';
export const ACCOUNT_CREATION = 'account_creation';
export const INTRODUCATION='introducation'
export const SIGNUP_FORM='signup_form'
export const OTP_SCREEN='otp_screen'
export const PASSWORD='password'
export const VERIFYMAIL='verifymail'
export const NOTVERIFIEDEMAIL='notverifiedemail'
export const INFORMATION='information'
export const USERTASTE='usertaste'
export const FINISH='finish'
export const SIGNUP_INTRO='signup_intro'
export const VERIFYIDENTITY='verify_indentity'
export const DOCUMENTSELECTION='documentselection'
export const CAMERASCAN='camerascan'
export const SHOWIMAGES='showimages'
export const FACERECOGNIZATION='facerecognization'
export const FACEIDENTITYINTRO='faceidentityintro'